### ISSUE TITLE
Nice crate!

### ISSUE THREAD

**Issue by dpc** [sile/sloggers#1]
I've added it to slog's README: https://github.com/slog-rs/slog#features--technical-documentation

**Comment by sile** [comment]
Thanks!
I like slog's design concept and it is very useful for me.

**Comment by dpc** [comment]
I am happy to hear that you like it.

Generally, I have a problem that the amount of details that `slog` exposes and crates it's split into, is scary and confusing for newcomers. So `sloggers` is exactly what is needed!

I have ended up putting links to it in more places, and I plan to make it the go-to convenience library for `slog`. It has a really good name (funny and clever!), nice documentation, and API that is intuitive.

If you have nothing against it, I'd like to integrate `slog` and `sloggers` experience a bit. 

* Make README more similar to what `slog-` libraries use
* to help newcomers find help: add link the slog's gitter channel

I'll also try to help to maintain (submit bugfixes, etc.) if time allows.

**Comment by sile** [comment]
> I plan to make it the go-to convenience library for slog.

Welcome!

Currently, `sloggers` has minimal features that are convenient for me, but
if you have ideas that improve this library, I would like to consider implementing it (if time allows).

**Comment by dpc** [comment]
All right. I'll be routing users here and /or reporting any issues as they arise.
