### ISSUE TITLE
The Trace level doesn't work

### ISSUE THREAD

**Issue by vessd** [sile/sloggers#10]
slog = "2.2.3"
sloggers = "0.2.6"

```rust
$ cat src/main.rs 
extern crate slog;
extern crate sloggers;

use slog::Drain;
use sloggers::{terminal, types::Severity, Build};

fn main() {
    let logger = terminal::TerminalLoggerBuilder::new()
        .level(Severity::Trace)
        .build()
        .unwrap();
    println!("{:?}", logger.is_trace_enabled());
}

$ cargo run
false
```

**Comment by sile** [comment]
By default, `slog` disables trace level logging. For enabling it, you need to specify `max_level_trace` feature to`slog`.
See [slog's documentation](https://docs.rs/slog/2.2.3/slog/#notable-details) for more details.

**Comment by vessd** [comment]
Thanks, it works.
Probably, it should also be noted elsewhere.
I followed the links
[slog](https://github.com/slog-rs/slog) → [Getting started](https://github.com/slog-rs/slog/wiki/Getting-started) → [slog - logging to terminal example](https://github.com/slog-rs/term/blob/master/examples/compact.rs) → [slog_term](https://docs.rs/slog-term/2.4.0/slog_term/) → [sloggers](https://docs.rs/sloggers/0.2.6/sloggers/)
and missed this note.

**Comment by sile** [comment]
As a possible thing on `slogger` side, I added [a brief note](https://docs.rs/sloggers/0.2.7/sloggers/types/enum.Severity.html#notice) about this behaviour.

**Comment by andrewbaxter** [comment]
If it's feature-disabled would it be possible to panic if a logger is set up with that level? I read the note, but I didn't remember it when I was knees deep in code and flipped the log level, and spent some time going crazy before I found this. (Maybe this is a slog issue instead)

**Comment by sile** [comment]
> If it's feature-disabled would it be possible to panic if a logger is set up with that level?

I'm not sure but it sounds difficult to accomplish that as `slog` seems not to provide API to get "the current enabled max level".

**Comment by andrewbaxter** [comment]
Ah right, yeah, makes sense.  I made this and forgot to link it here (in case anyone's interested) https://github.com/slog-rs/slog/issues/316
