### ISSUE TITLE
Add log file rotation

### ISSUE THREAD

**Issue by przygienda** [sile/sloggers#12]
says it all. would be super usefull ...

**Comment by sile** [comment]
Because `slogger`'s code become complicated if the functionality is implemented within the crate, I think it seems better to create another file rotation crate that used by `sloggers`.

**Comment by przygienda** [comment]
several observations: 

a) possible, probably too fine grain, I think it's better to put it into this crate
b) lots of code repetition between terminal and file, probably time for some generics ...

**Comment by sile** [comment]
> a) possible, probably too fine grain, I think it's better to put it into this crate

I am afraid that the requirement for the log rotation function will become complicated over time (e.g., file size based rotatin, time/date based rotation, old file deletion policy, old file compression, rotated file name pattern, etc).

If it is possible to restrict the functionalities to be supported by `sloggers` to limited and simple ones, I think it is reasonable to implement log rotation in this crate directly.

> b) lots of code repetition between terminal and file, probably time for some generics ...

I am sorry, I did not understand this intention very much ...
(I think console loggers are not related to file rotation)

**Comment by przygienda** [comment]
1. ok on the rotation, let's look @ first set of requirements. For me it's enough 
a. give size @ which it rotates
b. # of files it maintains maximums with a numbering scheme
c. optional compression of previous log by forking a process
2. what I meant: lots of code repeats between terminal and file submodules. May be worth starting to think how to write generics (like I wrote finalfuse) to unify code.

**Comment by sile** [comment]
> 2. what I meant ...

I understand and it sounds good. Thank!

> 1. ok on the rotation, ...

I grasped your requirements. Based on that, I will consider ways to support  log rotation on this weekend.

**Comment by sile** [comment]
Working branch for the feature: https://github.com/sile/sloggers/tree/basic-log-file-rotation

**Comment by sile** [comment]
I implemented the above `a` and `b` features in https://github.com/sile/sloggers/pull/14.
If you have any opinions, please comment on the PR.

**Comment by przygienda** [comment]
thanks much, wonderful stuff. I'm extending kvfilter @ same time & adjusting sloggers to adapt that. SLOG rocks ;-)
