### ISSUE TITLE
log file permissions ...

### ISSUE THREAD

**Issue by przygienda** [sile/sloggers#17]
It's often desirable on secure systems to restrict whether a log file is world-readable. It would be good to add something small to API sayiong "remove world readable when generating the log file" no matter what the umask says ...

**Comment by sile** [comment]
Is it sufficient to add `mode` option that specifies the umask value of the created files? ( https://doc.rust-lang.org/std/os/unix/fs/trait.OpenOptionsExt.html#tymethod.mode ).

**Comment by przygienda** [comment]
I do think so ... Even better solution
