### ISSUE TITLE
Support for record format

### ISSUE THREAD

**Issue by rohitjoshi** [sile/sloggers#22]
How do I format a record as `Timestamp|Level|Module:Line|Msg`
e.g.
`2019-03-14T07:13:58.740|INFO|abc::network_server:97|Starting connection handler child loop`

**Comment by sile** [comment]
`sloggers` only supports the formats defined by [`slog_term::CompactFormat`](https://docs.rs/slog-term/2.4.0/slog_term/struct.CompactFormat.html) and [`slog_term::FullFormat`](https://docs.rs/slog-term/2.4.0/slog_term/struct.FullFormat.html).
To keep this crate simple, sloggers probably does not provide custom message format functionality.
If you need it (or any other elaborate features), it is recommended to use [`slog`](https://docs.rs/slog/) directly.

**Comment by rohitjoshi** [comment]
Thanks. Any suggestions on how to override? I have been using slog with implementing log trait for a drain but missing some of the common capabilities of sloggers. E.g. log rotate, keep num of files, compression etc

**Comment by sile** [comment]
I tried adding [`BuildWithCustomFormat`](https://github.com/sile/sloggers/blob/custom-format/src/build.rs#L16) for this purpose (in `custom-format` branch).
It can be used as follows:
```rust
#[macro_use]
extern crate slog;
extern crate sloggers;

use sloggers::BuildWithCustomFormat; // Added
use sloggers::terminal::{TerminalLoggerBuilder, Destination};

let mut builder = TerminalLoggerBuilder::new();
builder.destination(Destination::Stderr);

let logger = builder.build_with_custom_format(|decorator| {
    let drain  = ...;  // Create your own drain that uses `decorator` (slog_term::Decorator).
    Ok(drain)
})).unwrap();
info!(logger, "Hello World!");
```

Is it sufficient for you?

**Comment by rohitjoshi** [comment]
Thanks, I will give a try. Appreciate your help.
