### ISSUE TITLE
Feature request: conditional dependency on gzip (libflate)

### ISSUE THREAD

**Issue by koba-e964** [sile/sloggers#24]
It looks like `libflate` is used only if `FileAppender::compress` is used. Maybe it's a possible idea to make this feature optional and allow users of this crate to opt-out dependency on `libflate`?

**Comment by koba-e964** [comment]
I mean this kind of change: https://github.com/sile/sloggers/commit/15c18c51853b37effc96feabe4c309ac25004672
(not yet confirmed to work properly, though)

**Comment by sile** [comment]
Sounds good.
If you can create a PR based on https://github.com/sile/sloggers/commit/15c18c51853b37effc96feabe4c309ac25004672, I would like to merge and review it.

**Comment by koba-e964** [comment]
PR sent: https://github.com/sile/sloggers/pull/25
