### ISSUE TITLE
v0.3.6 doesn't follow semantic versioning.

### ISSUE THREAD

**Issue by jcrevier** [sile/sloggers#27]
v0.3.6 added variants to `SourceLocation` a public enum and this wasn't versioned as a major release, so it breaks code built using cargo. Given this project does follow semantic versioning this should have been avoided.

**Comment by sile** [comment]
Thank you for creating this issue. Your suggestion seems reasonable. I'd like to publish v1.0.0 in the near future. I'll follow [the semantic versioning](https://semver.org/) after the release.

**Comment by jcrevier** [comment]
Thanks for taking it seriously. Also just a friendly reminder that Cargo's caret compatibility is [slightly different than SemVer before 1.0](https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#caret-requirements), which I could have explained better in my original issue. Nice to see a 1.0 release :)
