### ISSUE TITLE
Default terminal destination should probably be stderr

### ISSUE THREAD

**Issue by argv-minus-one** [sile/sloggers#31]
[The purpose of the `stderr` stream is error messages and diagnostics](https://en.wikipedia.org/wiki/Standard_streams#Standard_error_\(stderr\)), which is exactly what logging output is. But, currently, terminal logging defaults to `stdout`. Please consider changing this default to `stderr`.

**Comment by sile** [comment]
Thank you for creating this issue. Your opinion sounds reasonable and I'm positive to adopt the change. A difficult point is that it will break backward compatibility and we should need to wait to apply the change until the version 2.0.0 of `sloggers` is released (the date has not been determined yet).
