### ISSUE TITLE
Make pub enums and pub open structs non-exhaustive

### ISSUE THREAD

**Issue by argv-minus-one** [sile/sloggers#32]
If you're going to publish a breaking release (as discussed in #31), I suggest you also change your `pub enum`s, and those `pub struct`s whose fields are all `pub`, to be non-exhaustive where appropriate. That way, adding to them in the future (more options for `FileLoggerConfig`, more kinds of loggers for `LoggerConfig`, etc) will not be a breaking change.

## Motivation

I'm thinking about adding support for syslog via [the `slog-syslog` crate](https://docs.rs/slog-syslog/%2A/slog_syslog/) to sloggers. But, without the non-exhaustiveness I'm proposing here, adding support for syslog (or any other logging backend) to sloggers would be a breaking change.

### In Rust 1.40

If you require Rust ≥ 1.40, this is as easy as adding a [`#[non_exhaustive]`](https://doc.rust-lang.org/stable/reference/attributes/type_system.html#the-non_exhaustive-attribute) attribute to each affected `enum`/`struct`.

```rust
#[non_exhaustive]
pub enum LoggerConfig {
    File(FileLoggerConfig),
    Null(NullLoggerConfig),
    Terminal(TerminalLoggerConfig),
}
```

```rust
#[non_exhaustive]
pub struct TerminalLoggerConfig {
    /// Log level.
    #[serde(default)]
    pub level: Severity,

    // etc
}
```

### Before Rust 1.40

The old workaround is to add a `#[doc(hidden)] _NonExhaustive` variant to `enum`s and a non-`pub` empty field to `struct`s. The downside is that your code needs to handle the fake `_NonExhaustive` variant (probably by panicking).

```rust
pub enum LoggerConfig {
    File(FileLoggerConfig),
    Null(NullLoggerConfig),
    Terminal(TerminalLoggerConfig),
    #[doc(hidden)] #[deprecated = "internal use only"] _NonExhaustive,
}
```

```rust
pub struct TerminalLoggerConfig {
    #[serde(skip)]
    non_exhaustive: (),

    /// Log level.
    #[serde(default)]
    pub level: Severity,

    // etc
}
```

### Builders and Private `enum`s

Alternatively, you could replace open `struct`s with builders and keep `enum`s private. This is a much more drastic change, though.

```rust
#[serde(transparent)]
pub struct LoggerConfig(LoggerConfigInner);

enum LoggerConfigInner {
    File(FileLoggerConfig),
    Null(NullLoggerConfig),
    Terminal(TerminalLoggerConfig),
}
```

```rust
pub struct TerminalLoggerConfig {
    /// Log level.
    #[serde(default)]
    level: Severity,    // note: not pub

    // etc
}

#[derive(Default)]
pub struct TerminalLoggerBuilder(TerminalLoggerConfig);

impl TerminalLoggerBuilder {
    pub fn new() -> Self {
        Default::default()
    }

    pub fn build(self) -> TerminalLoggerConfig {
        self.0
    }

    /// Log level.
    pub fn severity(self, level: Severity) -> Self {
        self.0.level = level;
        self
    }

    // etc
}
```

**Comment by sile** [comment]
Thank you for the proposal. It sounds very nice.
I like the first approach which uses `#[non_exhaustive]` because of the simplicity.
It's welcome to create a PR to address this issue if you're interested.

> I'm thinking about adding support for syslog via the `slog-syslog` crate to sloggers. 

Great!
