### ISSUE TITLE
Expose drains

### ISSUE THREAD

**Issue by torsteingrindvik** [sile/sloggers#38]
I like the ability to create a rotating file logger:

```rs
FileLoggerBuilder::new("foo")
        .level(sloggers::types::Severity::Debug)
        .rotate_size(1024 * 1024)
        .rotate_keep(2)
        .truncate()
        .build()
        .expect("Couldn't setup logger")
```

However, I want to compose it with other stuff in slog.
It would therefore be nice if I could get the `Drain` instead of the `Logger`.

Could it be possible to have something like

```rs
FileLoggerBuilder::new("foo")
        .level(sloggers::types::Severity::Debug)
        .rotate_size(1024 * 1024)
        .rotate_keep(2)
        .truncate()
        .build_drain()
```

Or just `drain()` or something else entirely,
such that the end result is a `Drain`?

**Comment by sile** [comment]
Thank you for reaching out.

> `.build_drain()`

It seems a nice feature so I'll try to implement it next weekend.

**Comment by sile** [comment]
BTW, looking at [the doc of `slog::Logger`](https://docs.rs/slog/2.5.2/slog/struct.Logger.html), it looks like `Logger` implements `Drain`. Are there any problems to directly use `Logger` as a `Drain` implementation?

**Comment by torsteingrindvik** [comment]
@sile Thanks for your help!
I'm new to the "slog ecosystem" and seemed I jumped to conclusions too quickly.

You're right, using the `Logger` as a `Drain` works.

Here is my complete example:

```rust
    let stdout_drain = slog_async::Async::new(
        slog_term::FullFormat::new(slog_term::TermDecorator::new().build())
            .build()
            .filter_level(slog::Level::Warning)
            .fuse(),
    )
    .build()
    .fuse();

    let file_logger = FileLoggerBuilder::new("foo.log")
        .level(sloggers::types::Severity::Debug)
        .rotate_size(1024 * 1024)
        .rotate_keep(0)
        .truncate()
        .build()
        .expect("Couldn't setup logger");

    let stdout_logger = Logger::root(stdout_drain, o!());

    let drain = slog::Duplicate(stdout_logger, file_logger).fuse();

    let logger = Logger::root(drain, o!());

    debug!(logger, "Log to file only!");
    info!(logger, "Log to file only!");
    warn!(logger, "Log to both!");
    error!(logger, "Log to both!");
```

This works nicely for my use case which was:
* Log to file at debug level, but limit the size
* Log to stdout at warning level (nice colors is a bonus!)

**Comment by sile** [comment]
🎉
