### ISSUE TITLE
The log in the file is truncated when use json feature

### ISSUE THREAD

**Issue by Uchiha007** [sile/sloggers#45]
```
use actix_web::{middleware::Logger, web, App, HttpServer, Responder};
use slog::o;
use slog_scope::GlobalLoggerGuard;
use sloggers::{file::FileLoggerConfig, Config as SloggersConfigs};

#[actix_web::main]
async fn main() -> std::io::Result<()> {
    let guard = init_logger();
    guard.cancel_reset();
    let access_log_format =
        r#"%a %t "%r" %s %b "%{Referer}i" "%{User-Agent}i" "%{Request-Id}i" %T"#;

    HttpServer::new(move || {
        App::new()
            .wrap(Logger::new(&access_log_format))
            .service(web::scope("/actix").route("/slog", web::get().to(test)))
    })
    .bind(("0.0.0.0", 8082))?
    .run()
    .await
}

fn init_logger() -> GlobalLoggerGuard {
    let config_string = std::fs::read_to_string("configs/actix_slog_config.toml").unwrap();
    let log_config: FileLoggerConfig = toml::from_str(&config_string).unwrap();
    let logger = log_config.build_logger().unwrap();
    let logger = logger.new(o!("version" => "v0.1.0"));
    let guard = slog_scope::set_global_logger(logger.clone());
    slog_stdlog::init().unwrap();
    guard
}

async fn test() -> impl Responder {
    log::info!("this is from test");
    format!("Hello \n")
}
```
The  number of logs is also incorrect.

**Comment by sile** [comment]
Thank you for reporting this issue. I'll investigate that.
BTW, could you share the content of `actix_slog_config.toml`?

**Comment by Uchiha007** [comment]
[dependencies]
actix-web = "3.3.2"
log = "0.4.14"
slog = "2.7.0"
slog-scope = "4.4.0"
slog-stdlog = "4.1.0"
sloggers = { version = "2.0.0", features = ["json"] }
toml = "0.5.8"

**Comment by Uchiha007** [comment]
format = "json"
source_location = "local_file_and_line"
timezone = "local" # utc or local
level = "debug" # one of trace, debug, info, warning, error, critical
path = "/tmp/actix_slog.log"
channel_size = 10240 # slog async channel_size
rotate_size = 10240000
rotate_keep = 10
rotate_compress = false
truncate = false

**Comment by sile** [comment]
Thank you!

**Comment by sile** [comment]
Fixed the problem.
The cause was due to [`slog_json::Json`](https://docs.rs/slog-json/2.3.0/slog_json/struct.Json.html#method.default), by default, doesn't call `Write::flush()` for each log message. So the messages are stored in the buffer until they reach the buffer size limit.
#48 changed the behavior to enable flushing.
