### ISSUE TITLE
Logging in async context?

### ISSUE THREAD

**Issue by real-felix** [sile/sloggers#46]
Hi, sloggers is a great crate that does everything I need and more, but I want to use it in a web server, and I'm not sure if it is suitable for an async program. Will it block the task when I log? I'm especially thinking about the file logging that I want to use in production.

Thank you!

**Comment by sile** [comment]
Thank you for reaching out.
By default, `sloggers` builds asynchronous loggers, so you can use them for an async program (internally, [`slog-async`](https://docs.rs/slog-async/2.6.0/slog_async/) crate is used).

FYI: you can change the behavior via `channel_size()` and `overflow_strategy()` options (see [API doc](https://docs.rs/sloggers/2.0.0/sloggers/file/struct.FileLoggerBuilder.html) for more details).
