### ISSUE TITLE
set_stdlog_logger drops GlobalLoggerGuard

### ISSUE THREAD

**Issue by pingiun** [sile/sloggers#49]
It may be the case that I'm not using `set_stdlog_logger` correctly, however it does not seem to set the logger permanently because the `GlobalLoggerGuard` is dropped when the function returns.

From this documentation it seems you need to keep the guard alive until the end of the program:
https://docs.rs/slog-scope/4.4.0/slog_scope/struct.GlobalLoggerGuard.html

**Comment by sile** [comment]
Thank you for creating this issue. 
Your comment sounds right. 
I'm going to fix the problem soon.

**Comment by sile** [comment]
Fixed in #50. Thanks!
