### ISSUE TITLE
Merge custom-format feature to master branch

### ISSUE THREAD

**Issue by LuDiting** [sile/sloggers#55]
BuildWithCustomFormat part now only exists in custom-format branch, but I think it is really useful! 

Will you merge it to master branch in the future? So that I can use this feature from create.io by using package name and version number XD

**Comment by sile** [comment]
I am positive to merge the feature into the master branch 👍 
I will complete the task (possibly) within a week.

**Comment by LuDiting** [comment]
> I am positive to merge the feature into the master branch 👍 I will complete the task (possibly) within a week.

thank you so much XD

**Comment by sile** [comment]
Addressed in #57, and just released sloggers-2.2.0.
